# Docker environment
spring.datasource.url=jdbc:postgresql://postgres:5432/documents_db
spring.datasource.username=docuser
spring.datasource.password=docpass123
spring.jpa.hibernate.ddl-auto=update

minio.url=http://minio:9000
minio.public-url=http://localhost:9000

jwt.secret=${JWT_SECRET:ensia-dms-jwt-secret-key-for-lab-11-minimum-256-bits-long!!}

# Redis Cache (Exercise C1)
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis
spring.cache.redis.time-to-live=60000
